training:
  epochs: 150
  batch_size: 128
  z_dimension: 100
  update_interval: 50
optimizer:
  generator: 
    name: "adam"
    learning_rate: 0.0002
    beta_1: 0.5
    beta_2: 0.999
    epsilon: 0.0000001
  discriminator:
    name: "adam"
    learning_rate: 0.0002
    beta_1: 0.5
    beta_2: 0.999
    epsilon: 0.0000001
data:
  directory: dataset/imdb/ 
  mat_file: dataset/imdb/imdb.mat
  output_path: output/
  weight_path: weights/